
modLoader="javafml"

loaderVersion="[35,)"

license="GNU LESSER GENERAL PUBLIC LICENSE"

issueTrackerURL="https://github.com/Tiviacz1337/Travelers-Backpack/issues"

[[mods]]

modId="travelersbackpack"

version="5.3.4"

displayName="Traveler's Backpack"

updateJSONURL="https://gist.githubusercontent.com/Tiviacz1337/906937677aa472285dff9d6c2a189d5e/raw"

displayURL="https://www.curseforge.com/minecraft/mc-mods/travelers-backpack"

authors="Tiviacz1337"

description='''
Traveler's Backpack Mod for Minecraft 1.16.4!
'''

[[dependencies.travelersbackpack]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"