
modLoader="javafml"

loaderVersion="[40,)"

license="GNU LESSER GENERAL PUBLIC LICENSE"

issueTrackerURL="https://github.com/Tiviacz1337/Travelers-Backpack/issues"

[[mods]]

modId="travelersbackpack"

version="7.1.46"

displayName="Traveler's Backpack"

updateJSONURL="https://gist.githubusercontent.com/Tiviacz1337/906937677aa472285dff9d6c2a189d5e/raw"

displayURL="https://www.curseforge.com/minecraft/mc-mods/travelers-backpack"

authors="Tiviacz1337"

description='''
Traveler's Backpack Mod for Minecraft 1.18.2!
'''

[[dependencies.travelersbackpack]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.84,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelersbackpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
