
modLoader="javafml"

loaderVersion="[37,)"

license="GNU LESSER GENERAL PUBLIC LICENSE"

issueTrackerURL="https://github.com/Tiviacz1337/Travelers-Backpack/issues"

[[mods]]

modId="travelersbackpack"

version="6.0.31"

displayName="Traveler's Backpack"

updateJSONURL="https://gist.githubusercontent.com/Tiviacz1337/906937677aa472285dff9d6c2a189d5e/raw"

displayURL="https://www.curseforge.com/minecraft/mc-mods/travelers-backpack"

authors="Tiviacz1337"

description='''
Traveler's Backpack Mod for Minecraft 1.17.1!
'''

[[dependencies.travelersbackpack]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.travelersbackpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"